import logger from '../../core/logger/index.js';

/**
 * Safely parse JSON from raw LLM responses.
 * Handles markdown code block stripping (```json ... ```) and fallback structures.
 */
export function parseReviewResponse(rawText) {
  if (!rawText) {
    return {
      summary: 'No response generated by AI provider.',
      issues: [],
      suggestions: [],
    };
  }

  let cleaned = rawText.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.replace(/^```json/, '').replace(/```$/, '').trim();
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```/, '').replace(/```$/, '').trim();
  }

  try {
    const parsed = JSON.parse(cleaned);
    return {
      summary: parsed.summary || 'Code review completed successfully.',
      issues: Array.isArray(parsed.issues)
        ? parsed.issues.map((i) => ({
            line: typeof i.line === 'number' ? i.line : 1,
            severity: ['info', 'warning', 'critical'].includes(i.severity) ? i.severity : 'warning',
            category: i.category || 'style',
            message: i.message || 'Potential issue detected',
            suggestion: i.suggestion || '',
          }))
        : [],
      suggestions: Array.isArray(parsed.suggestions) ? parsed.suggestions : [],
    };
  } catch (err) {
    logger.warn({ err, rawText }, 'Failed to parse AI JSON response — returning unstructured review fallback');
    return {
      summary: rawText,
      issues: [],
      suggestions: ['Consider reviewing code logic manually.'],
    };
  }
}

export function parseExplainResponse(rawText) {
  return {
    explanation: rawText ? rawText.trim() : 'No explanation provided.',
  };
}

export function parseSuggestResponse(rawText) {
  return {
    suggestion: rawText ? rawText.trim() : 'No suggestions provided.',
  };
}
